name: animania
description: "Animania for watching any anime!"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.8.1
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  flutter_svg: ^2.0.10
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/ubuntu/
    - assets/fonts/league_spartan/
    - assets/icons/
    - assets/TEMP/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/ubuntu/Ubuntu-Italic.ttf
          style: italic
    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/league_spartan/LeagueSpartan-Thin.ttf
          weight: 100
        - asset: assets/fonts/league_spartan/LeagueSpartan-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/league_spartan/LeagueSpartan-Light.ttf
          weight: 300
        - asset: assets/fonts/league_spartan/LeagueSpartan-Regular.ttf
          weight: 400
        - asset: assets/fonts/league_spartan/LeagueSpartan-Medium.ttf
          weight: 500
        - asset: assets/fonts/league_spartan/LeagueSpartan-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/league_spartan/LeagueSpartan-Bold.ttf
          weight: 700
        - asset: assets/fonts/league_spartan/LeagueSpartan-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/league_spartan/LeagueSpartan-Black.ttf
          weight: 900
